name: Ejecutar Bot TVA

on:
  schedule:
    - cron: "0 * * * *" # Cada hora
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🛠 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        working-directory: .
        run: npm install --no-audit --no-fund

      - name: 🚀 Ejecutar bot
        run: node .github/bot.js
