# .github/workflows/bot.yml
name: TVA Price Bot

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

concurrency:
  group: tva-price-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install --no-audit --no-fund

      - name: Run bot
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          TVA_TOKEN_ADDRESS: 0x7324452980a5CeaD3EaDf1FA92c759390751cA13
          USDT_TOKEN_ADDRESS: 0xc2132D05D31c914a87C6611C10748AEb04B58e8F
          UNISWAP_ROUTER_ADDRESS: 0xE592427A0AEce92De3Edee1F18E0157C05861564
        run: node bot.js
