name: TVA Price Control Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Ejecutar cada 5 minutos
  workflow_dispatch: # Permite ejecución manual desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: https://polygon-rpc.com
        run: node bot.js
