name: Ejecutar Bot TVA

on:
  schedule:
    - cron: "0 * * * *" # Cada 60 minutos (en el minuto 0 de cada hora)
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🛠 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        working-directory: ./Control-price
        run: npm install --no-audit --no-fund

      - name: 🚀 Ejecutar bot
        working-directory: ./Control-price/.github
        run: node bot.js
