name: run-bot

on:
  schedule:
    - cron: "0 * * * *"  # Cada 60 minutos
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Instalar dependencias
        run: npm install --no-audit --no-fund
        working-directory: .

      - name: Ejecutar bot
        run: node bot.js
        working-directory: .
