name: TVA Price Bot

on:
  schedule:
    - cron: "*/7 * * * *" # Ejecuta cada 7 minutos
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci --verbose

      - name: Ejecutar bot
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          TVA_TOKEN_ADDRESS: ${{ secrets.TVA_TOKEN_ADDRESS }}
          USDT_TOKEN_ADDRESS: ${{ secrets.USDT_TOKEN_ADDRESS }}
          UNISWAP_ROUTER_ADDRESS: ${{ secrets.UNISWAP_ROUTER_ADDRESS }}
        run: node bot.js
